apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Chart.Name }}
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
