on:
    push:
        branches:
        - dev
name: Deploy spacedeck dev

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
      
        - name: Push to Docker Hub
          uses: docker/build-push-action@v1
          with:
              username: ${{ secrets.REGISTRY_USERNAME }}
              password: ${{ secrets.REGISTRY_PASSWORD }}
              repository: nclong87/private
              tag_with_ref: true
