on:
    push:
        branches:
        - dev
name: Deploy spacedeck dev

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t nclong87/private:spacedeck-open
            docker push nclong87/private:spacedeck-open
            
        - name: 'Deploy to Azure App Service'
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'nclong'
            slot-name: 'production'
            publish-profile: ${{ secrets.AzureAppService_PublishProfile_d0cebcfe3a254ebbbe332b3cbb989373 }}
            images: 'nclong87/private:spacedeck-open'
