on:
    push:
        tags:
        - '*.*.*'

name: Deploy spacedeck SPCE Production

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3
          with:
            ref: spce-prod

        - uses: actions/setup-node@v3
          with:
            node-version: 14

        - name: Set Release version
          run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

        - name: Cache node modules
          uses: actions/cache@v2
          id: npm-cache
          with:
            path: node_modules
            key: spacedeck-node_modules2-${{ hashFiles('**/package-lock.json') }}

        - name: Install Dependencies
          if: steps.npm-cache.outputs.cache-hit != 'true'
          run: |
            npm install
        - name: Build Style
          run: |
            gulp styles

        - name: 'Build and push image'
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        - run: |
            echo "Release version: ${{ env.RELEASE_VERSION }}"
            docker build -t spacedeck-open:${{ github.sha }} .
            docker tag spacedeck-open:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/spacedeck-open:${{ github.sha }}
            docker tag spacedeck-open:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/spacedeck-open:${{ env.RELEASE_VERSION }}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/spacedeck-open:${{ github.sha }}
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/spacedeck-open:${{ env.RELEASE_VERSION }}
