on:
    push:
        branches:
        - spce-prod
name: Deploy spacedeck SPCE Production

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master

        - name: Cache node modules
          uses: actions/cache@v2
          id: npm-cache
          with:
            path: node_modules
            key: spacedeck-node_modules-${{ hashFiles('**/package-lock.json') }}

        - name: Install Dependencies
          if: steps.npm-cache.outputs.cache-hit != 'true'
          run: |
            npm install
        - name: Build Style
          run: |
            gulp styles

        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t spacedeck-open:${{ github.run_id }}
            docker tag spacedeck-open:${{ github.run_id }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/spacedeck-open:${{ github.run_id }}
            docker tag spacedeck-open:${{ github.run_id }} ${{ secrets.REGISTRY_LOGIN_SERVER }}/spacedeck-open:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/spacedeck-open:${{ github.run_id }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/spacedeck-open:latest
